export const PROFILE_VALUES = [
  "Eerlijkheid",
  "Loyaliteit",
  "Humor",
  "Ambitie",
  "Rust",
  "Avontuur",
  "Familie",
  "Gezondheid",
  "Creativiteit",
  "Vrijheid",
  "Respect",
  "Spiritualiteit",
  "Empathie",
  "Groei",
  "Vertrouwen",
  "Openheid",
  "Communicatie",
  "Grenzen",
  "Gelijkwaardigheid",
  "Toewijding",
  "Stabiliteit",
  "Speelsheid",
  "Nieuwsgierigheid",
  "Dankbaarheid",
  "Optimisme",
  "Zelfzorg",
  "Authenticiteit",
  "Geduld",
  "Discipline",
  "Avontuurlijkheid",
];

export const PROFILE_PASSIONS = [
  // original
  "Reizen",
  "Sport",
  "Koken",
  "Muziek",
  "Kunst",
  "Boeken",
  "Natuur",
  "Gaming",
  "Film",
  "Tech",
  "Wandelen",
  "Fotografie",
  "Fitness",
  "Cycling",
  "Stedentrips",
  "Concerten",
  "Musea",
  "Design",
  "Ondernemen",
  "Vrijwilligerswerk",
  "Avontuur",
  "Boardgames",
  "Koffie",
  "Wijn proeven",
  "Podcast",
  "Buiten koken",
  "Wellness",
  "Honden",

  // expanded
  "Hardlopen",
  "Zwemmen",
  "Krachttraining",
  "Yoga",
  "Padel",
  "Tennis",
  "Voetbal",
  "Basketbal",
  "Klimmen",
  "Hiken",
  "Kamperen",
  "Roadtrips",
  "Strandwandelingen",
  "Picknicks",
  "City nightlife",
  "Brunch",
  "Bakken",
  "BBQ",
  "Speciaalbier",
  "Cocktails",
  "Restaurants ontdekken",
  "Thuis koken",
  "Sushi",
  "Italiaans eten",
  "Koffiebars",

  "Muziek maken",
  "Gitaar",
  "Piano",
  "Zingen",
  "Dansen",
  "Theater",
  "Comedy",
  "Festivals",
  "Documentaires",
  "Series",

  "Schrijven",
  "Tekenen",
  "Schilderen",
  "Interieur",
  "Mode",
  "Tattoo art",
  "DIY",
  "Handwerk",

  "Startups",
  "Investeren",
  "Productiviteit",
  "AI",
  "Apps",
  "Gadgets",
  "Fotobewerking",
  "Video editing",

  "Mindfulness",
  "Meditatie",
  "Self-improvement",
  "Psychologie",
  "Filosofie",
  "Spiritualiteit",
  "Astrologie",

  "Katten",
  "Dieren",
  "Paarden",
  "Koken met vrienden",
  "Gezelschapsspelletjes",
  "Escape rooms",
  "Quizzen",
  "Bowlen",
];

export const PROFILE_INTENTS = ["Serieuze relatie", "Casual", "Vriendschap", "Nog aan het kijken"];

export const PROFILE_RELIGIONS = ["Geen", "Christelijk", "Islam", "Joods", "Hindoe", "Boeddhist", "Anders"];

export const PROFILE_QUESTIONS = [
  "Wat is voor jou een perfecte zaterdag?",
  "Wat waardeer jij het meest in een relatie?",
  "Waar kijk je het meest naar uit dit jaar?",
  "Wat is een kleine gewoonte die je leven beter maakt?",
  "Wat wil je dat iemand over jou begrijpt vanaf het begin?",
];