export const TOOL_COSTS = {
  TEGENPOLEN_DUEL: 2,
  SCENARIO_SPIEGEL: 3,
  VERHALEN_DRIE_ZINNEN: 2,
  RELATIE_KOMPAS: 3,
  MATCH_SLOT_EXTENSION: 6,
  LIFESTYLE_FILTERS: 6,
} as const;

export const FREE_DEPTH_MOMENTS_TOTAL = 3;

export const MATCH_LIMIT_BASE = 5;
export const MATCH_LIMIT_EXTRA_MAX = 2;
export const MATCH_LIMIT_EXTENDED = MATCH_LIMIT_BASE + MATCH_LIMIT_EXTRA_MAX;
export const MATCH_SLOT_EXTENSION_HOURS = 24;
export const LIFESTYLE_FILTERS_DURATION_DAYS = 28;
